/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Can.h"
#include "AppScheduler.h"
IfxCpu_syncEvent g_cpuSyncEvent = 0;

void Message_Handler(void);
void event_100ms(void);

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
        

    Can_Init();
    AppScheduler_Init();
    while(1)
    {
        Message_Handler();
        CanMessage message;
        if(Check_Flag(FLAG_100MS))
        {
            Clear_Flag(FLAG_100MS);
            event_100ms();
        }

        if(CanTxQueue_Pop(&message))
        {
            CanMessage_Send(&message);
        }



    }
}

void Message_Handler()
{
    CanMessage msg = getCanMessage();
    if(msg.id != 0xfff)
    {
        switch(msg.id)
        {
            case DOOR_CONTROL_BCU_to_FDCU :
            {
                uint8 door_open = (uint8)CanMessage_Parse(msg.dataLow, msg.dataHigh, 0, 1);
                uint8 door_close = (uint8)CanMessage_Parse(msg.dataLow, msg.dataHigh, 1, 1);

                //door 동작
                break;
            }
            case RFID_CARD_RESPONSE_BCU_to_FDCU :
            {
                uint16 card_used_money = CanMessage_Parse(msg.dataLow, msg.dataHigh, 0, 16);
                uint8 card_id = (uint8)CanMessage_Parse(msg.dataLow, msg.dataHigh, 16, 8);
                uint8 card_status = (uint8) CanMessage_Parse(msg.dataLow, msg.dataHigh, 24, 2);
                uint8 card_people_count = (uint8)CanMessage_Parse(msg.dataLow, msg.dataHigh, 26, 6);

                //Rfid 동작
                //Mp3 동작
                break;
            }
            default :
                break;
        }
    }
}
void event_100ms(void)
{
    Message_Handler();

    CanMessage msg;
    CanMessage_Init(&msg, RFID_CARD_INFO_FDCU_to_BCU, 0x101, IfxMultican_DataLengthCode_6);
    CanMessage_AddSignal(&msg, 0, 32, 99600);
    CanMessage_AddSignal(&msg, 32, 8, 51);
    CanMessage_AddSignal(&msg, 40, 4, 2);
    CanTxQueue_Push(&msg);
}
